# Generated by Django 3.1.4 on 2021-01-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
